env:
  browser: true
  es2021: true
extends:
  - airbnb-base
  - plugin:solid/typescript
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
  - solid
rules: {
  "import/extensions" : "never"
}
