name: CI
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.3.0
      
      - name: Cache
        uses: actions/cache@v3.0.4
        with:
          path: app/node_modules
          key: cache-${{ hashFiles('**/package-lock.json') }}
  
      - name: Install and build
        run: |
          cd app
          npm ci
          npm run build
          mv 404.html dist/
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          cname: kieranwarwick.dev
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: app/dist
          publish_branch: gh-pages
          force_orphan: true
